import {chromium} from 'playwright';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import YAML from 'yaml';
import {openStore} from '../src/store.mjs';
import {createApp} from '../src/app.mjs';
const directory=await mkdtemp(path.join(tmpdir(),'kenxu-rules-ui-')),store=openStore(directory),servers=[];
let browser;
try{
 store.importSource(YAML.stringify({proxies:[{name:'Node A',type:'socks5',server:'127.0.0.1',port:1080},{name:'Node B',type:'socks5',server:'127.0.0.1',port:1081}],'proxy-groups':[{name:'Main',type:'select',proxies:['Node A','Node B']},{name:'Only B',type:'select',proxies:['Node B']}],rules:['DOMAIN-SUFFIX,baseline.example,Main','MATCH,Main']}));
 await store.createUser('owner','owner-rule-fixture',[],'admin');
 const alice=await store.createUser('alice','alice-rule-fixture',[store.inventory()[0].id]),bob=await store.createUser('bob','bobby-rule-fixture',[store.inventory()[1].id]);
 await store.setPassword(alice,'alice-rule-fixture');await store.setPassword(bob,'bobby-rule-fixture');
 const origins=[];
 for(const admin of [true,false]){let app;const server=http.createServer((req,res)=>app(req,res));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));servers.push(server);const origin=`http://127.0.0.1:${server.address().port}`;app=createApp({store,origin,admin});origins.push(origin);}
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.setDefaultTimeout(6000);page.on('pageerror',error=>errors.push(error.message));
 await page.goto(origins[0]);await page.locator('#login-form [name=username]').fill('owner');await page.locator('#login-form [name=password]').fill('owner-rule-fixture');await page.locator('#login-form [type=submit]').click();await page.locator('#admin-view').waitFor();
 await page.getByRole('button',{name:'规则管理',exact:true}).click();await page.locator('#rules-content').waitFor();await page.waitForFunction(()=>document.querySelector('#rules-content').value.includes('baseline.example'));
 await page.locator('#rules-content').fill('DOMAIN-SUFFIX,new.example,DIRECT\nMATCH,Main');await page.getByRole('button',{name:'校验并预览',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rules-preview-list').textContent.includes('new.example'));
 const saved=page.waitForResponse(r=>r.request().method()==='PUT'&&new URL(r.url()).pathname==='/api/admin/rules');await page.getByRole('button',{name:'保存规则',exact:true}).click();assert.equal((await saved).status(),200);
 await page.locator('#rules-owner').selectOption(alice);await page.waitForFunction(()=>document.querySelector('#rules-mode').value==='inherit'&&document.querySelector('#rules-content').disabled);
 await page.getByRole('button',{name:'复制当前导出规则为独立草稿',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rules-mode').value==='replace'&&document.querySelector('#rules-status').textContent.includes('草稿'));
 assert.ok((await page.locator('#rules-content').inputValue()).includes('new.example'));assert.equal(store.rulesState(alice).mode,'inherit','Copying a draft must not save it');
 await page.locator('#rules-mode').selectOption('prepend');await page.locator('#rules-content').fill(String.raw`PROCESS-PATH-WILDCARD,C:\Program Files (x86)\Example\*,DIRECT`+'\nDOMAIN-SUFFIX,personal.example,DIRECT');
 await page.getByRole('button',{name:'校验并预览',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rules-preview-list').textContent.includes('PROCESS-PATH-REGEX'));
 await page.getByRole('button',{name:'保存规则',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rules-status').textContent.includes('已保存'));
 assert.ok(store.config(store.getUser(alice)).includes('personal.example'));assert.ok(!store.config(store.getUser(bob)).includes('personal.example'));
 await page.locator('#rules-owner').selectOption(bob);await page.waitForFunction(()=>document.querySelector('#rules-content').disabled);assert.equal(await page.locator('#rules-content').inputValue(),'');
 await page.route('**/api/admin/users/'+alice+'/rules',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'fixture read failure'})}));
 await page.locator('#rules-owner').selectOption(alice);await page.waitForFunction(()=>document.querySelector('#rules-status').textContent==='fixture read failure');
 assert.equal(await page.locator('#rules-content').inputValue(),'');assert.equal(await page.locator('#rules-save').isDisabled(),true);assert.equal(await page.locator('#rules-reload').isEnabled(),true);
 await page.unroute('**/api/admin/users/'+alice+'/rules');await page.getByRole('button',{name:'重新载入',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rules-content').value.includes('personal.example'));
 let releasePreview,previewStarted,previewFinished;const held=new Promise(resolve=>releasePreview=resolve),started=new Promise(resolve=>previewStarted=resolve),finished=new Promise(resolve=>previewFinished=resolve);
 await page.route('**/api/admin/rules/preview',async route=>{const reply=await route.fetch();previewStarted();await held;try{await route.fulfill({response:reply});}finally{previewFinished();}});
 await page.getByRole('button',{name:'校验并预览',exact:true}).click();await started;
 await page.getByRole('button',{name:'用户管理',exact:true}).click();await page.locator('#users-list .user-row').filter({hasText:'bob'}).getByRole('button',{name:'配置规则',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#rules-mode').value==='inherit'&&document.querySelector('#rules-content').disabled);releasePreview();await finished;await page.unroute('**/api/admin/rules/preview');
 await page.waitForFunction(()=>document.querySelector('#rules-owner').value!==''&&document.querySelector('#rules-content').value==='');assert.equal(await page.locator('#rules-preview-list').textContent(),'');
 await page.locator('#rules-owner').selectOption(alice);await page.waitForFunction(()=>document.querySelector('#rules-content').value.includes('personal.example'));
 await page.locator('#rules-content').fill('DOMAIN-SUFFIX,blocked.example,Only B');await page.getByRole('button',{name:'保存规则',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rules-status').textContent.includes('未授权'));assert.ok(!store.config(store.getUser(alice)).includes('blocked.example'));
 page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'重新载入',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rules-content').value.includes('personal.example'));
 await page.getByRole('button',{name:'校验并预览',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rules-preview-list').textContent.includes('personal.example'));await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);});
 await mkdir('test-output',{recursive:true});await page.screenshot({path:'test-output/rules-admin-desktop.png',fullPage:true});
 await page.getByLabel('外观模式').selectOption('dark');await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>!document.body.classList.contains('nav-open'));await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);});await page.screenshot({path:'test-output/rules-admin-mobile-dark.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByRole('button',{name:'退出',exact:true}).click();await page.locator('#login-view').waitFor();assert.equal(await page.locator('#rules-content').inputValue(),'');assert.equal(await page.locator('#rules-preview-list').textContent(),'');
 await page.goto(origins[1]);await page.locator('#login-form [name=username]').fill('bob');await page.locator('#login-form [name=password]').fill('bobby-rule-fixture');await page.locator('#login-form [type=submit]').click();await page.locator('#user-view').waitFor();assert.equal(await page.getByRole('button',{name:'规则管理',exact:true}).count(),0);assert.deepEqual(errors,[]);
 console.log('PASS: private global/user rule editor, preview, inheritance, safe save errors, role isolation, 390px dark layout and logout clearing');
}finally{await browser?.close();for(const server of servers){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}store.close();await rm(directory,{recursive:true,force:true});}
