import {test} from 'node:test';import assert from 'node:assert/strict';import YAML from 'yaml';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';
import {shadowrocketSubscription,stashConfiguration} from '../src/mobile-subscription.mjs';import {clientImport,detectPlatform} from '../public/client-imports.js';import {openStore} from '../src/store.mjs';import {createApp} from '../src/app.mjs';
test('VLESS export preserves Reality/Vision and WSS data, unicode names and IPv6; unsupported transport fails closed',()=>{
 const nodes=[{name:'UK 🇬🇧',type:'vless',server:'2001:db8::1',port:443,uuid:'fixture-uuid',flow:'xtls-rprx-vision',servername:'sni.example','client-fingerprint':'chrome','reality-opts':{'public-key':'fixture-key','short-id':114514}},{name:'Relay',type:'vless',server:'gateway.example',port:443,uuid:'own-uuid',network:'ws',tls:true,servername:'gateway.example','ws-opts':{path:'/relay/v1?x=1',headers:{Host:'gateway.example'}}}];
 const raw=Buffer.from(shadowrocketSubscription(YAML.stringify({proxies:nodes})),'base64').toString(),[reality,ws]=raw.trim().split('\n').map(s=>new URL(s));assert.equal(reality.hostname,'[2001:db8::1]');assert.equal(reality.searchParams.get('sid'),'114514');assert.equal(reality.searchParams.get('flow'),'xtls-rprx-vision');assert.equal(decodeURIComponent(reality.hash.slice(1)),'UK 🇬🇧');assert.equal(ws.searchParams.get('type'),'ws');assert.equal(ws.searchParams.get('security'),'tls');assert.equal(ws.searchParams.get('path'),'/relay/v1?x=1');assert.equal(ws.searchParams.get('flow'),null);
 assert.throws(()=>shadowrocketSubscription(YAML.stringify({proxies:[{...nodes[0],network:'grpc'}]})));assert.throws(()=>shadowrocketSubscription(YAML.stringify({proxies:[{...nodes[1],'ws-opts':{headers:{Authorization:'private'}}}]})));assert.throws(()=>shadowrocketSubscription(YAML.stringify({proxies:[{...nodes[0],'dialer-proxy':'Other'}]})));
 assert.throws(()=>shadowrocketSubscription(YAML.stringify({proxies:[{...nodes[0],server:'fixture.example/other'}]})));assert.throws(()=>shadowrocketSubscription(YAML.stringify({proxies:[{...nodes[0],port:0}]})));
});
test('direct app imports retain the exact private URL and encode it; Android and iPad platforms select correct guides',()=>{
 const original='https://portal.example/s/fixture.yaml';for(const client of ['clash-verge','clash-meta','shadowrocket','stash']){const result=clientImport(original,client,720);assert.ok(result.scheme.includes(encodeURIComponent(result.remote)));assert.equal(new URL(result.remote).origin,'https://portal.example');assert.equal(new URL(result.remote).searchParams.get('format'),['shadowrocket','stash'].includes(client)?client:null);}
 assert.match(clientImport(original,'clash-meta').scheme,/update-interval=720/);assert.equal(detectPlatform({userAgent:'Mozilla Android'}),'android');assert.equal(detectPlatform({userAgent:'Macintosh',platform:'MacIntel',maxTouchPoints:5}),'ios');assert.throws(()=>clientImport('javascript:alert(1)','stash'));assert.throws(()=>clientImport(original,'__proto__'));
});
test('Stash adaptation retains authorized policies and rules while removing desktop-only assumptions',()=>{
 const config=YAML.stringify({proxies:[{name:'One',uuid:'own-uuid'}],'proxy-groups':[{name:'SG',type:'load-balance',strategy:'sticky-sessions',proxies:['One']}],rules:['PROCESS-NAME-WILDCARD,foo*,DIRECT','DOMAIN-REGEX,^example,SG','MATCH,SG'],dns:{nameserver:['desktop-private']},'rule-providers':{test:{type:'http',behavior:'domain'}}});const output=YAML.parse(stashConfiguration(config));assert.equal(output['proxy-groups'][0].strategy,'consistent-hashing');assert.equal(output.rules.length,2);assert.equal(output.proxies[0].uuid,'own-uuid');assert.equal(output.dns,undefined);assert.ok(!JSON.stringify(output).includes('desktop-private'));assert.ok(output['rule-providers']);
});
test('mobile subscription is grant-isolated, hides relay upstream credentials, preserves metadata and revokes with its base token',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'kenxu-mobile-')),s=openStore(dir);let server;
 try{s.importSource('proxies: [{name: Purchased, type: vless, server: private-upstream.example, port: 443, uuid: provider-secret, reality-opts: {public-key: provider-key}}, {name: Other, type: vless, server: other.example, port: 443, uuid: other-secret}]');const proxy=s.inventory()[0];s.meter.register(proxy.id,'Gateway',{clientTemplate:{server:'gateway.example',port:443,tls:true,network:'ws',servername:'gateway.example','ws-opts':{path:'/relay/v1'}}});const id=await s.createUser('mobile_friend','fixture-mobile-password',[proxy.id]);await s.setPassword(id,'fixture-mobile-password');server=createApp({store:s,origin:'http://127.0.0.1:4450'}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const token=s.subscription(s.getUser(id)),base='http://127.0.0.1:'+server.address().port+'/s/'+token+'.yaml',endpoint=base+'?format=shadowrocket';
 const response=await fetch(endpoint);assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/text\/plain/);assert.equal(response.headers.get('profile-update-interval'),'12');assert.match(response.headers.get('subscription-userinfo'),/total=107374182400/);assert.match(response.headers.get('cache-control'),/no-store/);const raw=Buffer.from(await response.text(),'base64').toString();assert.ok(raw.includes('gateway.example'));assert.ok(!raw.includes('provider-secret'));assert.ok(!raw.includes('private-upstream'));assert.ok(!raw.includes('other-secret'));assert.equal(raw.trim().split('\n').length,1);const stashReply=await fetch(base+'?format=stash');assert.equal(stashReply.status,200);const stash=YAML.parse(await stashReply.text());assert.equal(stash.proxies.length,1);assert.equal(stash.proxies[0].server,'gateway.example');assert.equal(stash.proxies[0]['reality-opts'],undefined);assert.equal((await fetch(endpoint,{method:'HEAD'})).status,200);assert.equal((await fetch(base+'?format=unknown')).status,400);s.rotate(id);assert.equal((await fetch(endpoint)).status,404);assert.equal((await fetch(base+'?format=stash')).status,404);const rotated=base.replace(token,s.subscription(s.getUser(id)));assert.equal((await fetch(rotated+'?format=shadowrocket')).status,200);s.setAccess(id,false,[]);assert.equal((await fetch(rotated+'?format=shadowrocket')).status,404);
 }finally{if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}s.close();await rm(dir,{recursive:true,force:true});}
});
